### ISSUE TITLE
[bug] properties Data and Expression not correctly read

### ISSUE THREAD

**Issue by Skrol29** [jbelien/MapFile-PHP-Library#2]
Hi have the following layer in a MapFile.

<pre>
  LAYER
    CONNECTION "xxxxxx"
    CONNECTIONTYPE POSTGIS
    DATA "geom from (
        SELECT eg.id, st_simplify(eg.geom, f_simplification(!BOX!)) AS geom, '%LEVELGEO%' as level_geo
        FROM t_entity_geo AS eg
        JOIN t_entity_level_parent_geo AS p 
            ON (eg.id=p.id_entity_geo) 
        WHERE (eg.geom && !BOX!) 
        AND (eg.id_level_geo = vm_level_geo('%LEVELGEO%'))  
        AND (p.id_entity_geo_parent IN (SELECT unnest(id_entity_geo_limite) 
            FROM t_context 
            WHERE id=%CONTEXT%))
        AND NOT st_isempty(st_simplify(eg.geom, f_simplification(!BOX!)))
    ) as t using unique id using SRID=4326"
    NAME "t_entity_geo_level_GEO_outline"
    PROJECTION
      "init=epsg:4326"
    END # PROJECTION
    STATUS OFF
    TILEITEM "location"
    TYPE POLYGON
    UNITS METERS
    VALIDATION
      "LEVELGEO"	".*"
      "CONTEXT"	".*"
    END # VALIDATION
    CLASS
      NAME "border Block1"
      EXPRESSION ('[level_geo]' eq 'B')
      STYLE
        ANGLE 0
        OFFSET 0 0
        OUTLINECOLOR 0 0 0
      END # STYLE
    END # CLASS
  END # LAYER
</pre>

If I read this file using `$m = new MapFile\Map('\my_mapfile.map');`

Then property _data_ of the first layer is empty,  and property _expression_ of the first class is empty.

When I write the map in a new file, the layer definition becomes :
<pre>  LAYER
    STATUS OFF
    NAME "t_entity_geo_level_GEO_outline"
    TYPE POLYGON
    UNITS METERS
    CONNECTIONTYPE POSTGIS
    CONNECTION "xxxxxx"
    PROJECTION
      "init=epsg:4326"
    END # PROJECTION
    CLASS
      NAME "border Block1"
      STYLE
        ANGLE 0
        OUTLINECOLOR 0 0 0
      END # STYLE
    END # CLASS
  END # LAYER</pre>

**Comment by jbelien** [comment]
Thanks for your return. I'll look into it !

**Comment by jbelien** [comment]
Sorry ... I just saw I forgot to fix EXPRESSION. I'll do that today !
