### ISSUE TITLE
[bug] Undefined variable: layer_data in layer.php on line 355 and 356

### ISSUE THREAD

**Issue by Skrol29** [jbelien/MapFile-PHP-Library#3]
I use a simple snippet with version 1.2.0
` $m = new MapFile\Map($fichier);`

and I have the error message 

> Undefined variable: layer_data in layer.php on line 355
> Undefined variable: layer_data in layer.php on line 356

Reading the corresponding code, the tiny thoughtlessness is obvious.

**Comment by jbelien** [comment]
Stupid me ! Thanks for the return !
